---
- hosts: all
  roles:
    - role: download-artifact
      download_artifact_api: https://softwarefactory-project.io/zuul/api/tenant/local
      download_artifact_pipeline: '{{ zuul.pipeline }}'
      download_artifact_job: '{{ build_job }}'
      download_artifact_type:
        - builddir
        - go-cachedir
        - go-mod-cachedir
      download_artifact_directory: '{{ zuul.project.src_dir }}'


  tasks:
    - name: Install requirements
      become: yes
      package:
        use: dnf
        name:
          - ShellCheck
          - bash-completion
          - bats
          - flatpak-session-helper
          - golang
          - golang-github-cpuguy83-md2man
          - meson
          - ninja-build
          - patchelf
          - podman
          - skopeo
          - systemd
          - udisks2

    - name: Set up artifacts
      shell: |
        # GOCACHE
        GOCACHE=$(go env GOCACHE)
        GOCACHE=${GOCACHE:-$HOME/.cache/go-build}
        rm -rf $GOCACHE
        mv ./$(basename "$GOCACHE") $GOCACHE
        # GOMODCACHE
        GOMODCACHE=$(go env GOMODCACHE)
        GOMODCACHE=${GOMODCACHE:-$HOME/go/pkg/mod}
        rm -rf $GOMODCACHE
        mv ./$(basename "$GOMODCACHE") $GOMODCACHE 
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: Setup submodules
      shell: |
        git submodule init
        git submodule update
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: Check versions of crucial packages
      command: rpm -qa *kernel* *glibc* golang podman conmon containernetworking-plugins containers-common container-selinux crun runc fuse-overlayfs flatpak-session-helper patchelf

    - name: Show podman versions
      command: podman version

    - name: Show podman debug information
      command: podman info --debug

    - name: Install Toolbox
      become: yes
      command: ninja -C builddir install
      args:
        chdir: '{{ zuul.project.src_dir }}'
        creates: /usr/local/bin/toolbox

    - name: Setup environment
      become: yes
      command:
        cmd: systemd-tmpfiles --create
        creates: /run/media
        creates: /run/host
