---
- hosts: all
  tasks:
    - name: Install requirements
      become: yes
      package:
        use: dnf
        name:
          - ShellCheck
          - bash-completion
          - bats
          - flatpak-session-helper
          - golang
          - golang-github-acobaugh-osrelease-devel
          - golang-github-briandowns-spinner-devel
          - golang-github-cpuguy83-md2man
          - golang-github-docker-units-devel
          - golang-github-fsnotify-devel
          - golang-github-godbus-dbus-devel
          - golang-github-harrymichal-version-devel
          - golang-github-mattn-isatty-devel
          - golang-github-sirupsen-logrus-devel
          - golang-github-stretchr-testify-devel
          - golang-github-spf13-cobra-devel
          - golang-github-spf13-viper-devel
          - golang-x-sys-devel
          - meson
          - ninja-build
          - patchelf
          - podman
          - skopeo
          - systemd
          - udisks2

    - name: Setup submodules
      shell: |
        git submodule init
        git submodule update
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: Check versions of crucial packages
      command: rpm -qa *kernel* *glibc* golang podman conmon containernetworking-plugins containers-common container-selinux crun runc fuse-overlayfs flatpak-session-helper patchelf

    - name: Show podman versions
      command: podman version

    - name: Show podman debug information
      command: podman info --debug

    - name: Set up build directory
      command: meson builddir
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: Build Toolbox
      command: ninja -C builddir
      args:
        chdir: '{{ zuul.project.src_dir }}'
        creates: builddir/src/toolbox

    - name: Install Toolbox
      become: yes
      command: ninja -C builddir install
      args:
        chdir: '{{ zuul.project.src_dir }}'
        creates: /usr/local/bin/toolbox

    - name: Setup environment
      become: yes
      command:
        cmd: systemd-tmpfiles --create
        creates: /run/media
        creates: /run/host
