name: Build the arch-toolbox image for PRs

on:
  pull_request:
    branches:
      - main
    paths:
      - images/arch/**
      - .github/workflows/arch-images-pr.yaml

jobs:
  build-and-push-images:
    name: Build the arch-toolbox image for PRs

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the arch-toolbox image
        uses: docker/build-push-action@v3
        with:
          context: images/arch
          file: images/arch/Containerfile
          platforms: linux/amd64
          push: false
          no-cache: true
          tags: quay.io/toolbx/arch-toolbox:latest
