name: "Images: Build and push Ubuntu toolbx images"

on:
  push:
    branches:
      - main
    paths:
      - images/ubuntu/**
      - .github/workflows/ubuntu-images.yaml
  schedule:
    - cron: '0 0 * * MON'

# Prevent multiple workflow runs from racing
concurrency: ${{ github.workflow }}

env:
  latest_release: '22.04'

jobs:
  build-and-push-images:
    strategy:
      matrix:
        release: ['16.04', '18.04', '20.04', '22.04', '22.10', '23.04']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: 'toolbx+github'
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push Ubuntu ${{ matrix.release }} toolbox image
        uses: docker/build-push-action@v3
        with:
          context: images/ubuntu/${{ matrix.release }}
          file: images/ubuntu/${{ matrix.release }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          tags: quay.io/toolbx/ubuntu-toolbox:${{ matrix.release }}

      - name: Push latest tag
        if: env.latest_release == matrix.release
        uses: docker/build-push-action@v3
        with:
          context: images/ubuntu/${{ matrix.release }}
          file: images/ubuntu/${{ matrix.release }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/toolbx/ubuntu-toolbox:latest
